### ISSUE TITLE
Access to N/W STRG DISC when aborting pushback ?

### ISSUE THREAD

**Issue by EisernUnion** [Fragtality/Fenix2GSX#1]
Hi,

im trying to get virtuali to understand my issue when aborting a pushback ..... on the fenix the N/W STRG DISC remains activated... any idea how to force to disable it by any variable ... i cant find any .....
Take a look at my post (a demo vid is included)

[http://www.fsdreamteam.com/forum/index.php/topic,29112.msg191712.html#msg191712](url)

thx for taking a look into it

**Comment by Fragtality** [comment]
Eliminating the Causes which require an Abortion of the Push-Back would be more reasonable imho. So if it is the Scenery, report it to the Scenery-Developer. If it happens that often that ATC requires to interrupt a Push-Back (highly unusual), I'd work on trying to understand the Instructions better - or get a GSX Profile which has the right Procedures needed for VATSIM/IVAO.

Also: Aborting the Push-Back is like a big red Killswitch - it is the last Resort if nothing else helps. If you where really required to Stop the Push-Back then use Stop Push-Back. There Reasoning behind the Fact that there are two Options.

I can't also really help how to (un)trigger the N/W STRG DISC Message and State. My Tool does nothing on Push-Back because there is no real Need to do something there with GSX & Fenix. That little desynchronisation between the Message and GSX insertion and removal of the Bypass Pin are just optics.

**Comment by EisernUnion** [comment]
When being on Vatsim and ATC tells you to stop pushback ... its like a big-red-stopbutton.... you have to stop right now....

Beside the ecam message ... there is some interaction "pushback_toggle" ... but sending pushback_toggle doenst work when gsx controls the pb ..... 
Hmmm.... strange.... hope virtuali will get my idea behind ....

Danke trotzdem :)

**Comment by Fragtality** [comment]
If you are told to Stop, and want to Stop - what is the Problem with using Stop? You're not Stopping, you're using an emergency kill-switch.

Yeah there is some Interaction, but not because there is some kind of Integration between the two. Imho it is just "by accident". Use either GSX or the EFB.

Don't know if he will get the Idea - because honestly: I also don't understand whether the Issue nor the Idea. Because Issue-Wise there is Stop to Stop, which works without breaking anything. And Idea-Wise it is nothing which FSDT can address - Fenix has to integrate with GSX.

**Comment by EisernUnion** [comment]
When hitting "Abort" ... NW Steering is blocked; Tug cant be disconnected in Fenix EFB.
The Problem is that aborting works like a nail lock police is using to stop cars. cars were stopped and cant move anymore... same with the fenix: You cant move the plan away...

You havnt looked the vid ?!

I found the solution: 

Sending L:FSDT_VAR_Frozen = 0

**Comment by Fragtality** [comment]
I have looked both Videos. That is why I'm telling you to use **Stop** to **Stop** 😉 
You are not asking for Stop, you are asking for the nail block 😅
