### ISSUE TITLE
INT/RAD switch not calling pushback

### ISSUE THREAD

**Issue by Terminal-Rat** [Fragtality/Fenix2GSX#13]
Hello,

I'm on RC3, aircraft is loaded, APU AVAIL and Bleed on (PCA removed by Fenix2GSX), Beacon ON (Fenix2GSX sets preparing for pushback and removes the jetway), moving the INT/RAD switch to INT is not starting the pushback sequence. It does work to call boarding during refueling, and I have not tested "During Push-Back to either Confirm or Abort the Push".

**Comment by vittorrio816** [comment]
I have a different flow, I do not turn the beacon on. So my aircraft is loaded, APU AVAIL and Bleed on (PCA removed by Fenix2GSX),moving the INT/RAD switch to INT is not starting the pushback sequence,

**Comment by Fragtality** [comment]
So you removed the Ground-Equipment by the normal Trigger of Beacon+Brake+ExtPwr?

I think this is the Issue. The Int/Rad "Shortcut" was specifically added for another Issue, to allow removing the Ground-Equipment without the Need to set the Beacon. Since the Ground-Equipment was already removed by the normal Trigger, it currently won't listen to the Push-Request by Int/Rad.

**Comment by Terminal-Rat** [comment]
> So you removed the Ground-Equipment by the normal Trigger of Beacon+Brake+ExtPwr?
> 
> I think this is the Issue. The Int/Rad "Shortcut" was specifically added for another Issue, to allow removing the Ground-Equipment without the Need to set the Beacon. Since the Ground-Equipment was already removed by the normal Trigger, it currently won't listen to the Push-Request by Int/Rad.

Correct

**Comment by vittorrio816** [comment]
> So you removed the Ground-Equipment by the normal Trigger of Beacon+Brake+ExtPwr?
> 
> I think this is the Issue. The Int/Rad "Shortcut" was specifically added for another Issue, to allow removing the Ground-Equipment without the Need to set the Beacon. Since the Ground-Equipment was already removed by the normal Trigger, it currently won't listen to the Push-Request by Int/Rad.

I do not remove the equipment, I leave it there and after the boarding is completed, and I see the final loadsheet countdown in the Fenix2GSX log, i press the INT button on the radio panel and leave it on.

**Comment by Fragtality** [comment]
Then see above :)

Fenix2GSX does not look for the Trigger anymore, since the Ground-Equipment was already removed.

**Comment by vittorrio816** [comment]
> Ground-Equipment was already removed.

what do you mean by this? that the ExtrPwr was set to off (Avail)? that still means that the ground equipment (GPU) is tere, as well as the chocks are there. Should i leeve ExtrPower on ON and then press INT? Disconnecting GPU while ON can be life threatening to the poor GSX ground guy :P

**Comment by Fragtality** [comment]
There are two Conditions/Trigger when Fenix2GSX will remove the Ground-Equipment:
1) Beacon ON + Brake SET + ExtPwr OFF
2) GSX Push-Back was called (does not matter who & how)

Fenix2GSX is currently only listening to the Int/Rad Switch if the Ground-Equipment is still there. But when reach Condition 1) it will not listen for it anymore. Since the Int/Rad Switch and that additional Ground-Equipment-Trigger where specifically added for not having the Beacon turned ON.

I'm currently investigating what can be done to make the Behavior more "universal".

**Comment by Fragtality** [comment]
Try [RC4](https://github.com/Fragtality/Fenix2GSX/releases/tag/v0.3.1-RC4)

**Comment by vittorrio816** [comment]
But I never reach condition 1, since my beacon remains off, so listening to INT should not stop. Will test RC4 tomorrow. Thanks for your support!

**Comment by Fragtality** [comment]
Oh sorry, misread your Post - I read "Beacon off" as "Beacon on" 😓

**Comment by Terminal-Rat** [comment]
RC4 works for my use case, thanks!

**Comment by vittorrio816** [comment]
I did a few tests but still no luck with the INT button. Tried pressing it for boarding (during refueling), also did not trigger. Starting to think that I might be doing something wrong. I press the INT button above the INT knob and leave it on (lit) while my beacon is on, GPU avail, parking brake on.

**Comment by Fragtality** [comment]
So the Issue persists for you with RC4?
Do you still have the Logs from these Tests?

**Comment by vittorrio816** [comment]
Yes, RC4, still got the logs.

**Comment by vittorrio816** [comment]
Problem lied between the keyboard and chair, it is now fixed. I was pressing the INT button, not INT/RAD switch. All works.
