### ISSUE TITLE
Priority to Select the Airline that Corresponds to the Airline You are Flying Rather than GSX's preferred choice! More of a Request for Improvement

### ISSUE THREAD

**Issue by mreza1st** [Fragtality/Fenix2GSX#19]
Hello,

Thanks for the great work. It would be great if the Airline services selected would first check the aircraft cfg file and select the airline accordingly and if none was available with GSX then go with GSX's choice. I am sure it's not an easy feature but it would nice. Also, can we donate to this project? I tried searching but couldn't find a place for donation.

Thanks again,

**Comment by Fragtality** [comment]
Won't be implemented:
- The Automation is just for Users which either don't care on the Operator (Fenix2GSX just selects the first Option). Or Users which have configured their Parkings to their preferred Operator as the only one (so GSX shows no Menu).
- Also I won't do any work for something FSDT could have implemented since AGES in GSX. It is a missing Feature of GSX - not Fenix or Fenix2GSX.
