### ISSUE TITLE
Boarding guideline

### ISSUE THREAD

**Issue by Adraesh** [Fragtality/Fenix2GSX#26]
Hello!

First of all thank you very much for this awesome mod.

I am quite confused with the boarding process.

I strictly followed your guideline for installation and configuration:

1. My aircraft is loading the Cold&Dark profile by default.
2. I load my simbrief flightplan
3. GSX automatically calls the refueling and catering services
4. Once the refueling truck is in place and asks me to set my desire fuel info I simply click load aircraft and chose Real time.
5. The boarding never starts.

So my question is simple:

What's the boarding procedure? Should I myself start the GSX Boarding manually? If so when exactly? Is the boarding supposed to be in synch with the Fenix EFB?

Thank you again!

**Comment by Fragtality** [comment]
You can of course start Boarding manually - the Main Mission of the Tool is the GSX Integratoin. All the Automations are just Sugar on top. You can disable all Automations, call every Service manually and still have the Integration.

But something is not right with your GSX Settings or GSX Aircraft Profile - GSX should not ask for the desired Fuel. Because it's only Job while Refueling "is looking good" (the Fenix still refuels it self).
So it is likely that the Aircraft never finishes Refueling (have you checked what the FOB is doing?) or the Way the Refueling works in your Case does not reach the right Condition for Fenix2GSX to start Boarding automatically. The Automation calls Boarding only after the Refueling has finished. You can manually intervene by calling Boarding from the GSX Menu (or use the INT/RAD Switch).

**Comment by Adraesh** [comment]
Hello,

Thank you for your prompt answer.

I re-try the whole process by checking the logs and my mistake was to click on the "Load Aircraft" button on the Fenix EFB.

The only thing that should be done from the Fenix EFB is to simply load the FlightPlan no need to click on Load Aircraft and everything works smoothly and everything is perfectly in synch.

That's really awesome what you did thank you very much.

Can't wait to see the future updates.

Problem resolved!

**Comment by Fragtality** [comment]
Thanks for the compliments 😃 

That's why I've warned in the Readme 😅 

> Be cautious on the Mass and Balance Page in the EFB: Don't change the planned Numbers, use "Load Aircraft" or "Reset All" - they likely break the Integration. "Resend Loadsheet" should not hurt though if needed! (In Case the Prelim-LS wasn't send automatically by the Fenix due to EOBT or because the Plane had no Power yet).
