### ISSUE TITLE
Boarding stops after 10 passengers

### ISSUE THREAD

**Issue by aerolou** [Fragtality/Fenix2GSX#29]
Hi, I really appreciate all the effort you put in this wonderful program. Everything works fine for, besides the fact, that boarding stops after 10 passengers. I tried the fixes listed on your page (check if **Username** is entered correctly and have **Ignore Time** checked). Also, I disabled **estimate passengers**, nonetheless boarding sadly still stops after passengers.

Do you have any idea what else could cause the issue?

Kind regards, Louis

**Comment by Fragtality** [comment]
The Passenger Density should not be higher than "Very Dense" - else too many Pax are Boarding in one Interval, triggering a Safeguard which ignores that Change.

Logs are always helpful btw. (In the Folder with the Binary, Fenix2GSX\<Date>.log)

**Comment by aerolou** [comment]
Checked that, passenger density is on normal. 
Still, boarding stops at 10 passengers :(.

Any ideas? I attached the log below the screenshots.

![image](https://github.com/Fragtality/Fenix2GSX/assets/94564210/e245ffcc-c738-486a-ba37-a72d7ef2156c)
![image](https://github.com/Fragtality/Fenix2GSX/assets/94564210/8be9cd4b-8ef2-4a80-a8c5-008d40aacfe1)
[Fenix2GSX20230814.log](https://github.com/Fragtality/Fenix2GSX/files/12333366/Fenix2GSX20230814.log)

**Comment by Fragtality** [comment]
Exactly as I expected - for whatever Reason, the Boarding happens to quickly.
You got one Change with 10 Passengers, then two Changes with over 15 Passengers at which Fenix2GSX ignores for being too big.

It seems to be the same Situation as in Issue #24 but this Time not being corrected through disable the "Estimate Passenger" Option 🤔 
Can you see the Passengers boarding? Is it a constant Flow or do they come in a tight & big Pack?

Don't really know what to do here, Fenix2GSX just follows the L-Vars that GSX presents.
Maybe try to to Check the Installation multiple Times in the FSDT Installer - maybe it wasn't updated correctly?
Do you have the Vehicle Acceleration enabled? Maybe that somehow also accelerates Passengers, leading to that Result.
Maybe also try to run with no other Addons (especially AI) - only Fenix, GSX and Fenix2GSX. Maybe it is a SimConnect Issue (it tends to go crazy if there to many Objects)?

Since your the second mysterious Case with that Effect, I'll look into adding a "hidden" Option (only configurable in the Config-File) that disables that Safe-Guard (which ignores a Pax-Change greater 15)

**Comment by Fragtality** [comment]
Try [RC12](https://github.com/Fragtality/Fenix2GSX/releases/tag/v0.3.1-RC12) and set ignorePaxSafeguard to "true" in the Fenix2GSX.dll.config File (do not start it before changed).

What does happen then at Boarding?

**Comment by aerolou** [comment]
I will check that later or tomorrow and will report back. Thank you for the effort!

**Comment by aerolou** [comment]
Good evening, I am very sorry for the inconveniences I caused. After doing a fresh GSX install, everything is working great with the normal version. Thank you so much for the big help tho it's great and makes flying so much more enjoyable!

**Comment by Fragtality** [comment]
No Worries. Glad to hear you could sort it out.
At least we have another Option to Troubleshoot in the Future 😅 
Btw, there is now also a dedicated Channel for Fenix2GSX on the GSX Discord ;)
