### ISSUE TITLE
Could we have an option to NOT close the cabin door automatically?

### ISSUE THREAD

**Issue by Airbumps** [Fragtality/Fenix2GSX#32]
Hello mate, 

Love this program!! Adds heaps to the immerson so thanks very much. Two things...

1. I was wondering if you could add a checkbox that prevents the main cabin door being closed automatically when GSX has finished boarding? I'm using Self Loading Cargo and usually GSX finishes boarding before SLC does. As such, about 60 seconds or so (or is it 90?) after boarding is finished, the main cabin door closes but SLC is still boarding. This causes a few issues.

2. Is there any way to have the GSX window close when some Fenix2GSX actions are completed. On my system the GSX window is staying open after the refueling/catering call has been made and when the jetway is disconnected prior to pushback. Just means I've got to close it manually.

In any event, love the app!!

**Comment by Fragtality** [comment]
Thanks!

1. Can't really relate to that, the Pax-Doors are closed when the Final LS is received (if not already closed during Equipment-Removal). That SLC still boards although GSX is finished boarding is a SLC Problem. Anyone can access the GSX L-Vars to read the Boarding state, so that should be fixed / proper implemented by SLC (especially when being a Payware Product). The Fenix still "self-loads" with Fenix2GSX, the Illusion of GSX doing that comes through synchronizing with the GSX L-Vars!
If that was a Stairs-Only stand: Please mind, that the Recommendation for "Automated Staircases" is semi-automatic (half-checked)
I might look into improving the Timings a bit: Starting the Countdown for the Final LS when GSX reports the Boarding Service as completed (instead of starting when Pax and Cargo are fully loaded). Also that the Doors closed after the Transmission has finished (instead of before it is started). That should move the Point of the Doors being closed a bit later 😉 

2. Well, that is why I recommend to disable the GSX Menu in the Readme 😉 (From Session-Start up until Push-Back Service is called, if all Automations are enabled. On Arrival you only need the GSX Menu for Gate-Selection. Then it can be disabled until Push-Back is active again)
If you own a StreamDeck and a registered Copy of FSUIPC, you can use the GSX Pro (or Fenix Profiles) for PilotsDeck. Then you never have to enable the GSX Menu because you have it on the StreamDeck.

**Comment by Fragtality** [comment]
Try [RC15](https://github.com/Fragtality/Fenix2GSX/releases/tag/v0.3.1-RC15) - It still won't be synchronized (that is a Task for SLC), but maybe it is a bit better that Way?

**Comment by Airbumps** [comment]
Mate version 15 was a significant improvement - Just so I understand the flow of whats going on its your utility that triggers the final load sheet being sent and then your utility that controls the final door closure? Neither of those are connected or linked by the Fenix.

In any event, the timings in RC15 are fantastic. love this utility!

**Comment by Fragtality** [comment]
Correct, the FinalLS is triggered by Fenix2GSX. Any only triggered - it is the exact same LS you would retrieve from the EFB.
The Doors are then closed if they are not already closed. Depending on the applied SOP, you can also start Push-Back without the FinalLS (where the Doors would be closed by GSX when Jetway/Stairs are removed)
