### ISSUE TITLE
Incorrect fuel amount loading

### ISSUE THREAD

**Issue by Berzerker** [Fragtality/Fenix2GSX#4]
New bug :)

Everything seemed to go as expected, but fueling stopped at around 8100 lbs, when I was planned around 18000, the fuel in the fenix EFB then updated to say ~8100 instead of the original planned 18000. 18000/2.2 is around 8100, so I suspect there's an issue with kg vs lbs going on.

Edit: Tried switching the unit to lbs/s instead and that didn't seem to make a difference. Simbrief and plane are both configured in lbs.

**Comment by Fragtality** [comment]
I'm very surprised of that to be honest 😮 
There was that Issue, yes - but that was already resolved many Versions ago.

Or at least it should have been. Maybe I got it somehow reintroduced by making the Refuel Speed configurable in either Unit.
Have to test it myself first.

Does it happen every Time? If that happens again it would be good to have the exact Simbrief-Flightplan at that time:
- Open the URL https://www.simbrief.com/api/xml.fetcher.php?userid=X
(where X is your numerical Simbrief ID)
- Save the resulting XML-Document as Text-File and attach it
- Also the Logs of Fenix2GSX please

**Comment by Fragtality** [comment]
Disregard the initial Message.

It is an Bug that got introduced with the ECAM ("REFUELG") Message.
The Tool did correctly refuel the Plane according to the planned Fuel - period!
It is just that it has (re)set the planned Fuel to kg instead of lbs 😆 🤣 

Try 0.2.9 :)

**Comment by Berzerker** [comment]
Well the fuel bug seems to have been fixed, but I think there's a new issue now. I have GSX audio control disabled, but my VHF1 is sticking to 118.100, even if I disable all options related to audio, it keeps automatically changing it to 118.100, and the volume control on the knob still works even if I disable it.

**Comment by Fragtality** [comment]
Moved to #5 
Fuel Issue fixed with 0.2.9

**Comment by Berzerker** [comment]
This is also somewhat fuel related, so I'll just post it here, if you'd like me to temporarily open a new issue, let me know.

I noticed I got this message today

> 2023-04-29 11:31:54.299 [INF] [ GsxController:RunLoadingServices ] Fuel Hose disconnected - waiting for next Truck 

Fueling stopped at some point in the middle and the fuel truck started to leave. Is this a GSX setting? Did this happen because the hose accidentally disconnected for some reason? Is there a way I can turn this off so that it always fuels in 1 trip?

**Comment by Fragtality** [comment]
Depending on the Situation that is completely normal!
I guess you where on a Position where Underground Refueling is not configured? The big Fuel-Truck which is used then has only a limited amount of Fuel (as IRL). When that truck is empty, GSX will disconnect the Hose and my Tool pauses Refueling and waits for the next Truck. Which should be send by GSX.

Yes there is a "Multiple Trips" Option in the GSX GUI. But it does also affect the Passenger Buses (so that there will only be one Bus with all Passenger in that)

**Comment by Berzerker** [comment]
I did know about that, but it seems like I already have that option disabled. I'll bring it up to Umberto and see what he says about it.

Thanks.

**Comment by Fragtality** [comment]
So a second Truck was not send?

Let us maybe gather some more Information first, or else it will just being pointed to my Tool - we need more proof ;)

**Comment by Berzerker** [comment]
It was the first time I'd seen it, so I actually restarted the flight since I thought it had loaded the wrong amount of fuel.

Looking back, the stand definitely was configured for underground fueling as I remember them bringing the fuel hose out to the outlet and connecting it.

I'll do some more testing and see if it comes up again.

**Comment by Fragtality** [comment]
That would be interesting ... the only Time GSX should disconnect the Hose although the Fuel Amount is still rising is when the Truck is empty. Else only when the Fuel is not increasing anymore (so the planned Fuel is on board).

Although we can not exclude that maybe SimConnect freaked out again and only returned Garbage. Because of that the L-Var for the Hose could have returned only zero, so Fenix2GSX was led to believe it was interrupted by GSX for the next Truck.

**Comment by Fragtality** [comment]
Okay ... Multiple Trips without underground Refueling can't happen - the Airbus does not have enough Capacity for that 🤣 

Plane with 0kg onboard, Flightplan with 18987kg (19000 max) => one truck ^^

**Comment by Fragtality** [comment]
Version 0.3.0 is out, you can try if that makes any difference for you.
When I receive no further Feedback or Information in the next 24 Hours, I'll close this Issue.
