### ISSUE TITLE
Turn-around with PCA?

### ISSUE THREAD

**Issue by AndersHogqvist** [Fragtality/Fenix2GSX#45]
The readme says "Make sure your Default State is set to either Cold & Dark or Turn-Around with APU" but from my experience "Turn-Around with PCA" works fine as well, or am I going to run into any issues using that state as default? If the PCA state isn't fully supported it would be nice to have that implemented.

**Comment by AndersHogqvist** [comment]
Oh and by the way, I LOVE this app! Super great work!

**Comment by AndersHogqvist** [comment]
I saw now that you mention Turn-Around with GPU under Usage - Pre-Flight as an acceptable startup state.

**Comment by Fragtality** [comment]
Yeah was pointed to Chewwy's Stream and saw that is was perceived as Problem.
Well, it isn't 😅 

The key Takeaway here is: Don't start with Engines running!
But I can't just write that because: you can start with Engines running - if you don't need any Departure-Services 😉 
Fenix2GSX will go directly to it's "Taxi-Out" State and removes the Ground-Equipment as a little QoL Improvement.
