### ISSUE TITLE
refueling rate

### ISSUE THREAD

**Issue by ashun99** [Fragtality/Fenix2GSX#46]
With the new version, i can not see the refuelling rate option. It used to be 28Kg/sec as default and modfiyable. Reading the RL fuelling, it appears to be around 12-15kg/sec. Is there a way i can modify that?

**Comment by Fragtality** [comment]
It is the same as it used to be. What is "RL fuelling"?

What is your Text Scaling set to in Windows?

**Comment by Fragtality** [comment]
Screenshot of UI pls

**Comment by ashun99** [comment]
![f2g](https://github.com/Fragtality/Fenix2GSX/assets/142121556/e0dc2e0f-5fea-4f7a-bc7b-801d730d186a)


RL=real life fueling

**Comment by Fragtality** [comment]
> RL=real life fueling

Ah, now I get it. It is about using another Rate, not that about that the actual Rate differs from the configured Value!


Well it is strange - I tested the UI with different Text Scaling Options on my Machine and did not saw that. 🤔 
What is your Resolution / Text-Scaling set to? The Screenshot seems a little strange to me: it is 4K but still the Window does not fit entirely on the Screen?!


What you could do as Work-Around for the Moment is to set it directly in the .config File (while Fenix2GSX is not running). It is the refuelRate and it is always given in kg/s (the unit is only for displaying comfort)

**Comment by ashun99** [comment]
Thanks a lto for such a prompt reply. it works with the change in config file.

**Comment by Fragtality** [comment]
Yeah sure!

But still would interesting to know why the automatic Scaling does not work as I had hoped.
So: What can you tell me Resolution and Scaling Wise on your Setup? 😉

**Comment by ashun99** [comment]
I have a  4k TV as monitor with 3840X2160  resolution. No idea about scaling. Where do i find it?

**Comment by Fragtality** [comment]
Ah okay, so it is native 4k what I saw in the Screenshot

Should be System -> Display in English I think - something with Scale there.

**Comment by ashun99** [comment]
scaling is 250%

**Comment by Fragtality** [comment]
I'm unable to reproduce that. When I set my Resolution to 4k (Nvidia DSR, since I don't have 4k Monitors) and even Scaling to 350% the the Refuel Rate Text-Box is not cut off.
What was interesting: even with that high Scaling, the Fenix2GSX did not look that big like in your Screenshots. It did look like that when I moved it to my other monitor still running 1440p - but even then not fitting on the whole Screen there was nothing cut off.

I'm a bit clueless right now tbh. There must be something different in your Setup which causes this 🤔

**Comment by Fragtality** [comment]
Was able to reproduce that - it seems you have an Additional Text-Scaling on Top of that general Scaling: Ease of Access -> Display -> Make text bigger.
Please confirm.

Still need to figure out what to do about that. The GUI is 100% standard WPF configured to automatically Scale with its Contents. So that is *Windows* Presentation Framework not working as intended on *Windows* - a classical Microsoft 😅

**Comment by ashun99** [comment]
with new link, its working perfectly. Thanks a lot. I can see refuelling rate option and modify it.

**Comment by Fragtality** [comment]
Excellent! Then happy Flights! 😃
