### ISSUE TITLE
Why forcing installation folder and not let user to choose ?

### ISSUE THREAD

**Issue by Jovzin** [Fragtality/Fenix2GSX#56]
Hello team,
I would like to know  why are you forcing the installation path and not provide option for user/s to choose it manually ?

This is not the first time I see that some 3rd party applications written by community are forcing users to not be able to choose their own installation folder.    What is going on  ? What is the reason for this ?  

Thank you. 
Jozef

**Comment by Fragtality** [comment]
Experience.

**Comment by Jovzin** [comment]
> Experience.

OK can you be more specific please ?

I would really like to know the reason. 
Thank you sir.
Jozef

**Comment by Jovzin** [comment]
> Experience.

Hello sir one more time. 
Very first thing : I am not a troll and I am not trolling or something simmilar.

I just would love to get a valid technical or normal explanation why forcing destination folder instead of giving option to choose ?
I see this trend more and more in 3rd party mods that are created by people from community that are creating mods in their free time. Forcing installation path of their mod like FS2CREW installing to C:/Program Files, your mod to C:/Users/xxx/AppData/Local , WoWUP to simmilar Appdata/Local folder.   
I really want to know why  and what is the reason for this ?    It is some limitation of the Microsoft Visual Studio ?  Or you need to be able to access faster some Windows dll libraries ?    From security perspective it is not good to install some unknown 3rd party apps to C where windows or some program files are. I for example have my C drive as sacred where only Windows and a few Programs can be, no 3rd party mods or addons for my games that I play. 

I am not a codder , I am more of a 3d asset creator working with Maya and Blender and I am really trying to understand this but somehow I am unable to.  Need a bit of helping hand from you not just one word.

Again nothing against you  , or against your mod. I think you are doing a great work. Just if you can give me a better explanation why is this trend happening in recent years, would help me to understand it better.

**Comment by Fragtality** [comment]
Sorry for the Delay, I was on a Business Trip.

I honestly don't know where the Problem is that any Software Installs to the Program Files. I mean the very Name shows that it is the indented Location of the Operating System for Programs.

On Fenix2GSX and the Core-Question: my Experience of the In-Experience from a considerable amount of Users showed, that it is not advisable to let them choose the Location. If they can't fail at (because they did not read and/or understand the Readme):
- Putting it in a Location where it can't write to it's .config File and can't create Logs
- Forgetting to set the Working Directory correctly depending how it is started (including completely not understanding what that means even if you tell them "cd to the Directory where you put it")
- Starting the wrong/old Version because they forgotten where they extracted the new Version

then they just have a better Experience in the End. Because it is ensured that at least the App can be started and run without Problems. And I have less Questions to Answer why it does not work/start. In the End it is easier that Way for Everyone involved.  In-Experienced Users don't have to worry how to do it. Experience Users have less Work. I have less Work.

On the Location chosen, AppData is just the correct and intended Location for App-Configuration-Files (and often also Log Files). So the Config and Log Location therefor would have been fixed to that anyways - it is just the right Thing to do. Also putting the Binary there seemed logical to me. The Motivation for the Installer was to make it easier and "failsafe" for the Users. To have less Work for me implementing it. Click-it-run-it-done.
Give what other Applications (especially MSFS) puts there as Caches and other Stuff, the ~100MB Binary Files of Fenix2GSX is just Water Drops in the Ocean. Is not *real* Problem for anyone. Only a perceived one for some because I took that Degree of Freedom. Also it is only that big because of the Fenix itself - the Tool could not do all the Things it does when I would not have included a Browser (CEF, Chromium Embedded Framework). My other Tools are considerably smaller. Why it even less matters there that I copy over the same Mechanics (like installing fixed into %appdata%). 
The only Thing that might be wrong to put it in AppData\Roaming (instead of Local) - but hey, if even *Microsoft* FlightSimulator fails to follow Guidelines for *Microsoft* Windows (in the bigger Picture of Windows Server, AD, Terminal Services), I don't really feel any guilt 😅 

What you need to Understand with Fenix2GSX: I wanted such a Tool. Therefore I made it. I just made it available for everyone, since I find it quite enjoyable and would have found it a bit egoistic to keep it for myself. Especially if I did that with other Tools/Stuff before. But that is an extra Amount of Work - and I don't earn anything with it. Maybe to a Degree, because some of the Feedback and Feature Requests made it better and better and with some Features I could not live without anymore too (like mapping Apps to other ACP Knobs).
What I want to say with that: I don't have any Motivation to please the User so that he uses my Tool - in the Sense of I don't care how many "Copies I sold". I don't care - take it or leave it!  😉 

But yes: On the other Hand it would be advisable for Developers who sell their Tools to have the Motivation of pleasing the User (e.g. ease the Installation and Usage Experience) - for their own Good alone.
I can't really tell why "the Professionals" don't do that sometimes - I don't earn my Money as Developer, it's just my Hobby.

From a general User Standpoint, my View is that Software which needs big Amounts of Capacity should really allow that (big in the Sense of multiple 10's and 100's of GB). Anything smaller should not impose a *real* Problem on a modern and decent PC (especially when used for Flight Simming). 
In my own User-Experience I don't really have Problem with the Install Locations to be honest. The Stuff which I feel would "clutter" my System Drive allows putting it elsewhere. And/Or allows to define where the Data is stored at least. I have a dedicated 1TB System Drive - because it is just "contemporary" imho.

I hope that answers your Question(s) a bit more extensive 😜
