### ISSUE TITLE
VHF2 unusable with Fenix2GSX open

### ISSUE THREAD

**Issue by GrantCrackers18** [Fragtality/Fenix2GSX#6]
I like to use VHF1 and VHF2 while flying on VATSIM, but whenever Fenix2GSX is open, my VHF2 becomes unusable. I have the audio panel setup correctly, but I can't hear anything. Once I completely close F2GSX, my audio comes back.

![image](https://user-images.githubusercontent.com/28992240/235314976-ff1b7d13-fc9f-4d06-9c18-51ab28ef88ab.png)

**Comment by Fragtality** [comment]
Uhm okay, can't imagine how that should happen.

So vPilot is configured as VHF1 App and you can control the Audio-Volume with the VHF1 Knob (ACP1)?

Please provide the exact Steps and Settings so that I can reproduce that.

**Comment by GrantCrackers18** [comment]
To be completely honest I haven't used the VHF1 Audio Volume feature within F2GSX. I will try to fly next flight with/without it to see if that somehow changes the behavior, as well as get some steps for you. I didn't do anything special, but this is only my second flight with the app.

**Comment by Fragtality** [comment]
What do you mean by "haven't used the VHF1 Audio Volume feature" ?
The Thing is, vPilot is set by default:

So that either means you changed that in the GUI to nothing, in which Case it should not control the vPilot Volume any longer (as last step before stopping the Control it sets the App-Volume to 100% and to unmuted, if the App is running).

Or it means you have not changed that Setting in the GUI and it did control vPilot Audio. But I could not see any Effect in a quick Test (without connection) when I selected VHF2 for transmit or receive. Please note that when you deselect VHF1 for receive, vPilot will be completely muted. The Volume Control of Fenix2GSX works on the OS-Level - the whole Audio-Session of the respective Application is controlled. And with that all the "virtual Channels" an App may provide.

**Comment by GrantCrackers18** [comment]
https://streamable.com/o97zrx

Here's a video showing the behavior. You can see the settings and everything, once I completely close F2GSX my audio is restored.

**Comment by Fragtality** [comment]
That is exactly what I have described.

**Comment by GrantCrackers18** [comment]
Missed that, my mistake. Is there any way to not have that happen?

**Comment by Fragtality** [comment]
Depends.
You can of course disable that Feature of Fenix2GSX - just remove vPilot in the GUI (so the Textbox in the GUI is empty).
But when that Feature is enabled, the VHF1 Knob is the Volume-Control-Knob for the whole vPilot App.

If the Knob is pulled was specifically chosen for mute / unmute - so that muting/unmuting leaves the Volume Level intact (and being quicker than turning it 0). So that will not Change.
I think I'll add another CheckBox for the VHF1 Volume-Control for it to be enabled/disabled that Way. Should be more intuitive and would allow to change that Setting more quickly if it is just for enabling/disabling.

But I need to think about it, if add any other Check or so. Sure, I could monitor the VHF2-Rec-Latch also and prevent the Mute if it is pulled ... but then the Volume-Level of vPilot would still be controlled by the VHF1-Knob. That could also interfer with Use-Cases where a User specifically wants to have the VHF1-App muted even when VHF2 is pulled. So I would need other Check-Boxes for the if & how and that all adds more complexity and thus likelyhood for Bugs ... but at the Moment I want to get it in a State to share it with a wider Audience (through flightsim.to) 🤔

**Comment by Fragtality** [comment]
After I've looked up how it is working on the FSL, I'd go for this Compromise: The Mute/Unmute by Push/Pull of the Record Latch is now a configurable Option which defaults to false:

![image](https://user-images.githubusercontent.com/78614902/235357532-33ddf963-7720-4214-a205-5ebcc25b2063.png)

What do you think? :)

**Comment by GrantCrackers18** [comment]
Sounds good to me, thanks again for looking into this
