### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by alexwalkerinfo** [Fragtality/Fenix2GSX#63]
Was looking to make some tweaks, but cannot see any source code (only image files). Are you using Github purely for issue tracking?

Cheers

**Comment by Fragtality** [comment]
It is because I (somewhat) agreed with Fenix that Parts of it should not be public. So there is no Way to build your own Variant I'm afraid!
(But if it would be for Reference I could share the core "GSXController")

What would those Tweaks be? Maybe I find one them reasonable 😅 
(It's not like that I would not be open for Suggestions/Ideas ... it just that most of them lately where just because People are lazy/fancy)

**Comment by Fragtality** [comment]
No further Feedback => Closed
