### ISSUE TITLE
Fuel truck is not departing

### ISSUE THREAD

**Issue by DomWin02** [Fragtality/Fenix2GSX#65]
Hey there!

I set all options as related in the Manual. But the fueltruck is not departing after refueling. Also the Catering trucks are not arriving. Also upon boarding passenger board yes, but no cargo is loaded.

**Comment by Fragtality** [comment]
Shall I directly close the Issue or can I expect this Time to get any more Information than that?

**Comment by DomWin02** [comment]
> Shall I directly close the Issue or can I expect this Time to get any more Information than that?

Oh wow... what a friendly kind of support!

Then tell me what information do you need!

**Comment by Fragtality** [comment]
Well, I mean what do you expect when I just closed another Issue of yours because no further Information was provided? Also considering the general and documented Support Policy where I already made an Exception for that previous Issue?
<br/>

Here again a Screenshot from the Readme

![image](https://github.com/Fragtality/Fenix2GSX/assets/78614902/b6392f97-4b8d-472b-9531-24ca3c63b800)

**Comment by DomWin02** [comment]
[Fenix2GSX20240119.log](https://github.com/Fragtality/Fenix2GSX/files/13988526/Fenix2GSX20240119.log)

**Comment by DomWin02** [comment]
To describe to problem: I've setted up as described in the read me, with the option catering will be after refueling. Refueling starts and finished but not departes from the plane. so because of that catering will not arrive. Also cargo loading doesnt started.

**Comment by Fragtality** [comment]
Yes, all these Services use the same Side of the Airplane. Because of that GSX only allows one Service to be active. That is nothing I could control.
The only Exception is when Catering is immediately called after ("together with") Refuel (which you chose not to use).

What I can see in the Logs is a Mix between the usual SimConnect Issues and wrong Usage:
![image](https://github.com/Fragtality/Fenix2GSX/assets/78614902/c876841c-c46f-43ba-8495-7e13ea0e245e)
![image](https://github.com/Fragtality/Fenix2GSX/assets/78614902/3e12664c-4804-46a8-a91f-1c4c22039e50)

- It is completely fine if you want to have Catering after Refuel, that is why there is an Option. But please don't start Boarding in the Gap between Refueling and Catering then!
- Try if disabling (or enabling) the Progessive Refuel Option helps (see Readme for the exact Name). I did have a Case on the 787 where the Truck did not want to leave although the Plane was finished Refueling fine. In that case disabling that Option helped.
- But not sure if that helps at all, since Entries like "Fuel Hose disconnected ..." and "Passenger Delta was below ..." are more indicative of an SimConnect Issue (since the Variables suddenly are 0). Maybe some of the Tips in the Troubleshooting help, maybe not - that is just sadly the State of MSFS (still) :/
- Also it seems you have restarted Fenix2GSX to resolve the Issue? That was a bit too much because you also reset the State of Fenix2GSX (e.g. that Refueling was already called & completed). But when carefully timed, resetting GSX may help. E.g. ending the Refuel with a GSX restart might have worked (without also calling Boarding manually that is)

**Comment by DomWin02** [comment]
Thanks for reply. I will test it on the next flight. The Fuel Truck problem is now solved^^ Catering is now set to come with refueling and it worked.
