### ISSUE TITLE
XML Exception

### ISSUE THREAD

**Issue by SeattleSummers** [Fragtality/Fenix2GSX#66]
I keep on trying to install it and it is now crashing my sim on every load. The only time it runs properly is without configuring autostart, but I try to remove or configure it in any way it keeps on giving me ''System.Xml.XmlException' during AutoStartExe'. I've tried it with and without antivirus as well as restarted my computer multiple times, as well as deleting the folder in the appdata folder and redownloading the installer.
[Fenix2GSX20240119.log](https://github.com/Fragtality/Fenix2GSX/files/13996734/Fenix2GSX20240119.log)
[Report.txt](https://github.com/Fragtality/Fenix2GSX/files/13996750/Report.txt)

**Comment by Fragtality** [comment]
Hmm, how does your EXE.xml look like?

**Comment by SeattleSummers** [comment]
The exe.xml is empty 
![image](https://github.com/Fragtality/Fenix2GSX/assets/157193837/1f59b8ab-817f-4a4e-933c-a62513beb78e)

**Comment by SeattleSummers** [comment]
After another round of attempting to restore the FSDT backup exe.xml it took, closing, thanks for your time

**Comment by Fragtality** [comment]
Well, you're not done yet 😄 

It would be important to know if Fenix2GSX was the Reason for that empty File or it just encountered an empty File! The Latter is something which would not really be a Fenix2GSX Problem - an empty File is per-se invalid/malformed and Fenix2GSX (Installer) throwing an Exception on that is just a Symptom of a different Root-Cause.

BUT: If Fenix2GSX would really create an empty File this is surely interesting. Because it should not really happen! It deserializes that File to actual Objects (~the Installer "understands" the Structure and Contents) with the *Microsoft* Library for that (the non-gamy Part of Microsoft). And then it writes the whole File (with *all* it Contents) back. So even if it would be blocked to write the File - you still would have at least your old File.
So if that wasn't the Case it would be good to troubleshoot that in order to fix that or add some Tips to the Troubleshooting Section for other Users!

So make another Backup of your current working exe.xml (to be sure) and try installing Fenix2GSX again. If that results again in an empty File, please send me that Backup (and ofc restore it^^). Either I can reproduce it here or we know that there is something else/more in your Setup.

**Comment by SeattleSummers** [comment]
I ran the installer again and it didn't write anything to the new exe.xml, here's the backup file, 
[exe - Copy.txt](https://github.com/Fragtality/Fenix2GSX/files/14000243/exe.-.Copy.txt)

**Comment by SeattleSummers** [comment]
(sorry for the additional message, i misread the last one) I ran the installer again and it came out untouched, everything is in there as it was before.

**Comment by Fragtality** [comment]
Okay, so Fenix2GSX did not produce the empty File?
Maybe I add some kind of Check/Message that the User are informed directly that the File is empty (instead of a "random" Exception) 🤔 

What I wonder a bit is the File you have attached. From the Auto-Start-Entries it looks completely normal, but the Header is totally strange. 😳 

This  is your *exe.xml*:
```xml
<?xml version="1.0" encoding="Windows-1252"?>
<SimBase.Document Type="SimConnect" version="1,0">
  <Descr>SimConnect</Descr>
  <Filename>SimConnect.xml</Filename>
  <Disabled>False</Disabled>
```
This is mine:
```xml
<?xml version="1.0" encoding="Windows-1252"?>
<SimBase.Document Type="Launch" version="1,0">
  <Descr>Launch</Descr>
  <Filename>EXE.xml</Filename>
  <Disabled>False</Disabled>
  <Launch.ManualLoad>False</Launch.ManualLoad>
```
