### ISSUE TITLE
Exception during Update Error while copying content to a stream.

### ISSUE THREAD

**Issue by sm4051** [Fragtality/Fenix2GSX#69]
Thank you for continuing work on Fenix2GSX! I prefer it for additional features, especially the passenger number randomization. 

I'm running into an issue on 0.4.5 with Fenix block 2. Refueling does not seem to work and I'm receiving continuous "Exception during Update Error while copying content to a stream." in the log. Thank you for any help!

![image](https://github.com/Fragtality/Fenix2GSX/assets/86208597/da88a999-c8e5-4368-ad4f-016d1f46ccd0)
[debug.log](https://github.com/Fragtality/Fenix2GSX/files/14449782/debug.log)
[Fenix2GSX20240229.log](https://github.com/Fragtality/Fenix2GSX/files/14449802/Fenix2GSX20240229.log)

**Comment by Fragtality** [comment]
Well, I know thanks to the Logs in which Function/Part that is happening - but I'm still puzzled why that is. 🤔 

Could you describe a little how you use the EFB? (Only external Device? Only Cockpit? Both? Is the Cockpit EFB hidden? Which side in the Cockpit?)
Because from the first Look it seems Fenix2GSX can't get any Information from the Fenix - Communication is blocked somehow.

What also may help to isolate the Error: Can you try with 0.4.4? (Since downgrade: Backup and then remove the config in %appdata%\Fenix2GSX)
Does it throw the same Error? (Generally it should work up to the Cargo - so Refuel and Pax Boarding should work when the Cargo Doors are operated manually)

**Comment by Fragtality** [comment]
❗ 
Please check if this only happens on the IAE?

**Comment by Fragtality** [comment]
Try that
https://www.mediafire.com/file/kbdy8vp9khzqe3o/Fenix2GSX-Installer-v0.4.6.exe/file

**Comment by sm4051** [comment]
I use the EFB only cockpit. Both CAPT and FO EFB's are visible. I use the CAPT side EFB.

I have confirmed 0.4.4 gives same error using B2, and 0.4.4 worked great for me before Fenix B2.

I have not had a chance to test CFM, but I can confirm this is happening on IAE.

**Comment by sm4051** [comment]
> Try that https://www.mediafire.com/file/kbdy8vp9khzqe3o/Fenix2GSX-Installer-v0.4.6.exe/file

No error using this version! Thank you.

**Comment by Fragtality** [comment]
Version 0.4.6 released
(You still need to update it, there where additional Changes for Door/Stair Handling)
