### ISSUE TITLE
GPU after parking

### ISSUE THREAD

**Issue by joxterboi** [Fragtality/Fenix2GSX#75]
After landing in my company we almost never start the APU. When parking we shut down ENG 2 and the ground personal connect the GPU, only then we shut down ENG 1.

Would it be possible to add an option for this type of operation. Maybe connect GPU soon after parking brake is set not checking engine state.

Many thanks, this addon really makes the fenix come alive on the ground!

**Comment by Fragtality** [comment]
Hmm, and let me guess the Beacon stays of course on until after ENG1 was shutdown?

No that won't be implemented, my Policy is to not implement everybody's special SOPs in an Automatic Flow. On top of that it would require refactoring/rewriting so much Parts which currently just work, that it would just not be reasonable.

BUT: Fenix2GSX should at least allow for manually handling such special SOPs and not impede them. What I could do is add an Option (only available in the config File) so that Fenix2GSX won't remove the already manually placed GPU in such Situations.
(Currently it removes the automatically placed GPU and Chocks since these are not tied to the Beacon State - a Situation equally "wrong" for others)

**Comment by joxterboi** [comment]
Yes the beacon stays on.

Sound like a good compromise, in older versions I was able to connect the gpu via the tablet but now as you said it removes it.

**Comment by Fragtality** [comment]
How does that work for you?
https://www.mediafire.com/file/un9qniutvyu4pmx/Fenix2GSX-Installer-v0.4.10.exe/file

Run the Installer as normal (yes, it will report 0.4.9 - that is normal for Dev-Builds).
Then run Fenix2GSX once and close it after a few Seconds. Now you should see the *interceptGpuAndChocks* Parameter in your Config File (%appdata%\Fenix2GSX) - change that to *false*.

**Comment by joxterboi** [comment]
Hi again,

It works! Now I can connect gpu manually again, thank you.
Just a question, is it possible to make it so that they don't disconnect the GPU when calling the tug for pushback?

**Comment by Fragtality** [comment]
It is slowly loosing Sense to use something like Fenix2GSX then? It is about not to care about the Ground-Equipment.

But, first and foremost - does GSX even allow for your SOPs? Can you start an Engine with HP Air and *then* Push-Back at all?!

And you are aware that there are two Triggers to remove Ground-Equipment?
