### ISSUE TITLE
Loadsheet

### ISSUE THREAD

**Issue by paulwain** [Fragtality/Fenix2GSX#77]
Is there any chance we can get the loadsheet when importing the flight plan from the EFB like how it was before instead of getting both loadsheet and prem load sheet when loading and fuelling is complete. 

Only reason being, I also use the FS2crew app and need to input info for the departure brief like the take-off CG.

**Comment by Fragtality** [comment]
As it currently stands: No.

Before B2 the Prelim was automatically send by the EFB. If it was not send automatically (e.g. Time Differences, Plane not powered up) the EFB at least allowed the user to Resend the Loadsheet (which Fenix2GSX just triggered automatically for you).
Since B2 removed these Features, it would be a Feature Request you would need to direct at Fenix.

Maybe there would be some a Way, but I just can't figure it out without Help. Which I don't receive.

**Comment by paulwain** [comment]
Ah okay, thank you for your reply. Hopefully fenix will sort it out :P
