### ISSUE TITLE
Critical Exception during ServiceLoop

### ISSUE THREAD

**Issue by deepdiver70** [Fragtality/Fenix2GSX#78]
Hello! Got this message.. What does this imply?
![image_2024-04-16_192341552](https://github.com/Fragtality/Fenix2GSX/assets/80041465/606313a2-514a-4760-8ace-cff191bc6e4a)

**Comment by Fragtality** [comment]
Update.

**Comment by deepdiver70** [comment]
Hey! This is on the updated version - I’ve just completed the update ^^

**Comment by Fragtality** [comment]
And you are on Fenix 2.0.0.407 ?!

**Comment by deepdiver70** [comment]
Oh I thought you meant fenix2gsx. I apologise for the inconvenience - thanks for your patience. :)

**Comment by Fragtality** [comment]
Well, I actually meant Fenix2GSX - because that would be the exact Symptoms/Error Messages with the previous Fenix2GSX Version and the current Fenix Version. That's why there was an Update yesterday to make it compatible (which in Turn makes the current Fenix2GSX of course incompatible to older Fenix Versions).

So either update the Fenix or downgrade Fenix2GSX! 😉
