### ISSUE TITLE
More likely a "feature request"

### ISSUE THREAD

**Issue by fresH229a** [Fragtality/Fenix2GSX#8]
Hey,

just found your addon yesterday and its absolutly amazing!

I just got an idea, dont know if this is possible to implement, but how about 1-2 more external Programs to manage the volume in the sim, like via HF1/2.

If we are flying we mostly are in Teamspeak or Discord and sometimes, if ATC is busy you need to mute you or turn the volume of TS/Discrod down. It would be cool, if the we can also do that in Sim, like via HF1/2 knobs (which are not really used yet).

Cheers!
Bernd

**Comment by Fragtality** [comment]
Hello fresh,
thanks, glad to hear that! 😃 

Hmm, not in the near Future though. It took some Time to get the whole Audio-Control to the current State and there is still a mysterious Bug on Windows 11 which specific Setups it seems. And generally the whole Idea was to bring a FSL-like Integration to the Fenix - which has already been surpassed since the VHF1 App there was hardcoded.
Adding more Apps would absolutely require this time to refactor and abstract the Code. The Core-Mechanics are the same for any App, but since it was only VHF1 to be added back-then the Code is just "copy & pasted" at the Moment.

But I'll save it for someday later 😉

**Comment by manni2811** [comment]
Whenever your software requests refueling or boarding, the GSX menu will open. Why is that? However, the program should prevent the pilot from being distracted from his cockpit preparation flow. But you still have to click away the menu window. Since I can operate GSX better manually.

**Comment by Fragtality** [comment]
1) Please don't hijack just any Topic
2) It opens because it is operating the GSX Menu
3) Read the Readme:
> If you set every Option for automatic Service Calls, I'd recommend to disable the GSX Menu in the Toolbar (Icon not white). The Services are still called, but you won't see the Menu popping-up. So Push-Back, De-Ice and Gate-Selection are the only Situations where you need to open it.

4) You don't need to use the Automations to have the Integration, if you prefer operating GSX manually (also stated in the Readme)

:wink:

**Comment by Fragtality** [comment]
@fresH229a 
Implemented in [RC8](https://github.com/Fragtality/Fenix2GSX/releases/tag/v0.3.1-RC8) - please Test!

**Comment by Fragtality** [comment]
Closed, implemented
