### ISSUE TITLE
Refuel service active when flightplan isn't yet active

### ISSUE THREAD

**Issue by DavidEGTE** [Fragtality/Fenix2GSX#88]
![image](https://github.com/user-attachments/assets/fa904856-aadb-47a0-98e5-72aaae727222)
Strange that I yet not imported a flightplan and the fuel service already there
v0.4.12 
Airbus A321 IAE
[Fenix2GSX20240831.log](https://github.com/user-attachments/files/16825028/Fenix2GSX20240831.log)

**Comment by Fragtality** [comment]
Well, I don't know.

The Addon never has send a "3" to the GSX Menu, so it can not even have called Refuel by accident.<br/>
I would rather look if you have any interfering Stuff that automates GSX. Maybe the Fenix forgotten the Settings, maybe something with Fs2Crew or even my own GSX_AUTO Script (the Search Strings have to be modified so that the Script disables itself for all Fenix Variants - https://discord.com/channels/1011680327346966590/1139939827886854144/1276526399674388543). <br/><br/>

The only Thing that worries me a bit (but could also be just an Indicator the Fenix had an Issue there) - is the one Exception in the Update Call where the SeatMap is initialized.
Is there anything special on that Livery cabin-wise? For example is this the 2 Class Layout? Is that GSX Seated Passenger fanciness applied?

**Comment by Fragtality** [comment]
No further Feedback => Closed
