### ISSUE TITLE
.net Installer Issue

### ISSUE THREAD

**Issue by JamieEC** [Fragtality/Fenix2GSX#90]
I am getting an error downloading .net.
![image](https://github.com/user-attachments/assets/f3298e65-3dcb-4b4a-8929-0007d660632b)

Can you let me know which file I need so I can install manually?

**Comment by Fragtality** [comment]
Have you retried it? Maybe it was just a random Issue (e.g. because some other App in the Background making a ton of http Requests)
Or it can also be an Issue that some AV/Firewall Software is blocking the Request.

In any way: you need the .NET 8 Desktop Runtime (Win x64): https://download.visualstudio.microsoft.com/download/pr/907765b0-2bf8-494e-93aa-5ef9553c5d68/a9308dc010617e6716c0e6abd53b05ce/windowsdesktop-runtime-8.0.8-win-x64.exe
But still run the Installer after that. And when Installing a major .NET Runtime Release for the first Time, it is good practice to reboot the PC.

**Comment by Fragtality** [comment]
No further Feedback => Closed
