### ISSUE TITLE
Pax Boarding now after cargo finished ?

### ISSUE THREAD

**Issue by EisernUnion** [Fragtality/Fenix2GSX#94]
Hi,

since the last update i observe that pax boarding starts minutes (sometimes 5, sometimes 15 minutes) after cargo has finished....... is there a reason for ?

**Comment by Fragtality** [comment]
No.
Mind the Support-Policy: even when considering that as meaningful Description, there are still the Logs missing.

What might be, is that GSX did not work properly because the Tug Question wasn't answered. It should be auto-answered, but I suspect that does not happen when the GSX Menu is disabled (which would be the normal Situation at that Point when using Fenix2GSX).
If that is the Issue you had there, the current Dev-Build might help:
https://www.mediafire.com/file/onivvm86edi8jg4/Fenix2GSX-Installer-v0.4.15.exe/file

**Comment by EisernUnion** [comment]
I think that could be the issue ..... now it took 22 Minutes until they started boarding.... i will give it a try.

**Comment by Fragtality** [comment]
> What tug question ? What has the tug to do with boarding ?

RTFM, or in that case: RTFUN 😂 
https://www.fsdreamteam.com/couatl_liveupdate_notes.html

**Comment by Fragtality** [comment]
> 0.4.15 works fine .... ! .... but there is still this "Tug Question" .... Is there an update at Pilotsdeck and/or Fenix GSX Profiles needed ?

No, there is no Change needed in the Aircraft Profile (or Airport Profiles). It just connects the Tug when Boarding is happening - nothing new to define there.

What has Pilotsdeck to do with that?

**Comment by EisernUnion** [comment]
Because (as i was looking for the 'tug question') i just saw there is something which needs a respond "Yes No (GSX Choice)" .. i assume its that question... disapears when pressing the "GSX Menu" Button on StreamDeck

**Comment by Fragtality** [comment]
Ohhh, you mean because of the GSX-Auto Script! Well, that is hopelessly deprecated by now anyway ^^

I think / hope you should be fine on the Fenix where it is for the most part disabled and should not do any Menu Refreshes at that Point which would interfere with the Question. As far as I can remember 😅 

The "irony" about the whole Situation: I'm happy myself and with the Feedback on how the new PilotsDeck Version runs. The updated Profiles are all tested and polished. The new (PilotsDeck-only-non-FSUIPC) GSX Script worked well.
And just as I was to complete my last Test-Cycle before releasing all the new Stuff on this Weekend, FSDT dropped that "Weekend-Update-Bomb" so I was busy the whole (Flightsim-Part of the) Weekend figuring out the absolutely-not-confusing Implementation  of it. So back to test everything through again. *yay*

<br/>

>  i just saw there is something which needs a respond "Yes No (GSX Choice)" 

You seeing it doesn't mean it was there - how dare you to assume to such strange Conclusions! 😂 
That is just how the GSX Menu works - it just does not update when such Questions where answered. It stays at the last Question. For Example that is exactly what happens when a Operator Selection happens. The Reason that you don't see that Question anymore and instead see the real State of the Menu is because GSX-Auto/Fenix2GSX forced a Menu Refresh in the meantime. Or put differently: the Reason you have (I hope?) a good User Experience is because GSX-Auto/F2G use the GSX Menu the wrong respectively the you-are-not-to-supposed-to-do-what Way! 😉

**Comment by EisernUnion** [comment]
hmmm...... the best user experience with gsx would be that i never have to open it :) .... but when the gsx auto-script on pliotsdeck get deprecated how do i answer the pushback directions etc .... (thats literally the only use-case , ok and look at the boarding numbers (no of pax / % of cargo) to know when to start-up the apu

**Comment by Fragtality** [comment]
Like that, soon ^^

![image](https://github.com/user-attachments/assets/c0479e88-2320-4b58-bea5-97e3ee249f2f)

**Comment by EisernUnion** [comment]
almost ... :)

![image](https://github.com/user-attachments/assets/7b09d310-1a10-457b-9f58-7d65b954a166)

**Comment by Fragtality** [comment]
Closed => Update now pushed as Release
